version: '3.8'

services:
  job-server:
    build: .
    container_name: job-aggregation-api
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=sqlite:////app/data/job_board.db
      - API_PORT=8001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Optional: Add Nginx reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: job-api-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - job-server
  #   restart: unless-stopped
